package com.emmisolutions.emmimanager.model;

public enum PatientIdLabelType {
    PATIENT_SELF_REG_LABEL_PATIENT_ID,
    PATIENT_SELF_REG_LABEL_MEMBER_ID,
    PATIENT_SELF_REG_LABEL_MEDICAL_RECORD_NUMBER,
    PATIENT_SELF_REG_LABEL_MRN,
    PATIENT_SELF_REG_LABEL_OTHER
}
